source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'redcarpet', '~> 3.5.1'
gem 'middleman', '~> 4.4.0'
gem 'middleman-autoprefixer', '~> 3.0.0'
gem 'middleman-search', github: 'workarea-commerce/middleman-search'
gem 'middleman-navtree', '~> 0.1.10'
gem 'puma', '>= 4.3.1'
